##############################
# combine the checkM summaries into one text file for dRep
# 2025-04-23
##############################

universe = vanilla
executable = combine_summaries.sh

#transfer_input_files = R1-2010-08-31_S37_L001_R1_001.fastq.gz, R1-2010-08-31_S37_L001_R2_001.fastq.gz

#Logs info
log = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/combine_$(cluster)_$(sample).log
output = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/combine_$(cluster)_$(sample).out
error = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/combine_$(cluster)_$(sample).err

#Operational parameters
request_cpus = 5
request_memory = 20GB
request_disk = 10GB

#Variables
location = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis
arguments = $(sample) $(location) 
queue sample from samples.txt

