##############################
# Identify which dereplicated MAGs are medium to high-quality 
# 2025-04-01
##############################

universe = vanilla
executable = copy_final_bins.sh

#transfer_input_files = R1-2010-08-31_S37_L001_R1_001.fastq.gz, R1-2010-08-31_S37_L001_R2_001.fastq.gz

#Logs info
log = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/select_bins_$(cluster)_$(MAG).log
output = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/select_bins_$(cluster)_$(MAG).out
error = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/select_bins_$(cluster)_$(MAG).err

#Operational parameters
request_cpus = 4
request_memory = 20GB
request_disk = 10GB

#Variables
location = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis
arguments = $(MAG) $(location) 
queue MAG from /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/results/quality_MAGs/final_bin_set_unique.txt

