##############################
# map Pancho reads and JGI reads to 4 MAGs
# 2025-05-06
##############################

universe = vanilla
executable = coverm_more_reads.sh

#Logs info
log = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/coverm_$(cluster).log
output = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/coverm_$(cluster).out
error = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/coverm_$(cluster).err

#Operational parameters
request_cpus = 4
request_memory = 20GB
request_disk = 10GB

#Variables
location = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis
arguments = $(reads) $(location) $(request_cpus)
queue reads from coverm_more_reads_loc.txt
