##############################
# map phosphatis, regalis, TKFM, and EPV1 to samples using coverM
# 2025-05-10
##############################

universe = vanilla
executable = coverm_4_MAGs.sh

#Logs info
log = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/coverm_$(cluster).log
output = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/coverm_$(cluster).out
error = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/coverm_$(cluster).err

#Operational parameters
request_cpus = 16
request_memory = 200GB
request_disk = 10GB

#Variables
location = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis
arguments = $(location) $(request_cpus)
queue

