##############################
# edit checkM file for dRep 
# 2025-03-27
##############################

universe = vanilla
executable = edit_checkm_file.sh


#Logs info
log = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/edit_checkm_$(cluster)_$(sample).log
output = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/edit_checkm_$(cluster)_$(sample).out
error = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/edit_checkm_$(cluster)_$(sample).err

#Operational parameters
request_cpus = 4
request_memory = 20GB
request_disk = 10GB

#Variables
location = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis
arguments = $(sample) $(location)
queue sample from samples.txt

