universe = vanilla
executable = metag_transfer.sh

#transfer_input_files = R1-2010-08-31_S37_L001_R1_001.fastq.gz, R1-2010-08-31_S37_L001_R2_001.fastq.gz
log = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/metag_transfer_$(sample).log
output = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/metag_transfer_$(sample).out
error = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/metag_transfer_$(sample).err

request_cpus = 1
request_memory = 2GB
request_disk = 1GB

arguments = $(reads) $(sample)
queue reads,sample from mapping_file.txt
 

