##############################
# template
# 2025-XX-XX
##############################

universe = vanilla
executable = "EXECUTABLE.sh"

#Logs info
log = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/$(cluster).log
output = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/$(cluster).out
error = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/$(cluster).err

#Operational parameters
request_cpus = 16
request_memory = 200GB
request_disk = 10GB

#Variables
location = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis
arguments = $(bin) $(location) $(request_cpus)
queue sample from samples.txt

