##############################
# Transfer gtdbtk database from GLBRC to home directory, then untar it
# 2025-04-25
##############################

universe = vanilla
executable = transfer_gtdbtk_data.sh

#transfer_input_files = R1-2010-08-31_S37_L001_R1_001.fastq.gz, R1-2010-08-31_S37_L001_R2_001.fastq.gz

#Logs info
log = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/transfer_gtdbtk_$(cluster).log
output = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/transfer_gtdbtk_$(cluster).out
error = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis/logs/transfer_gtdbtk_$(cluster).err

#Operational parameters
request_cpus = 4
request_memory = 200GB
request_disk = 10GB

#Variables
location = /home/glbrc.org/jusmith/CRISPR_Phage_Analysis
arguments = $(location) 
queue

